In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import statsmodels.api as sm
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
dta=sm.datasets.fair.load_pandas().data

In [4]:
dta.head(2)

   rate_marriage   age    ...     occupation_husb   affairs
0            3.0  32.0    ...                 5.0  0.111111
1            3.0  27.0    ...                 4.0  3.230769

[2 rows x 9 columns]

In [5]:
dta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6366 entries, 0 to 6365
Data columns (total 9 columns):
rate_marriage      6366 non-null float64
age                6366 non-null float64
yrs_married        6366 non-null float64
children           6366 non-null float64
religious          6366 non-null float64
educ               6366 non-null float64
occupation         6366 non-null float64
occupation_husb    6366 non-null float64
affairs            6366 non-null float64
dtypes: float64(9)
memory usage: 447.7 KB

In [6]:
dta['affair']=(dta['affairs']>0).astype(int)

In [7]:
dta.head(2)

   rate_marriage   age  yrs_married   ...    occupation_husb   affairs  affair
0            3.0  32.0          9.0   ...                5.0  0.111111       1
1            3.0  27.0         13.0   ...                4.0  3.230769       1

[2 rows x 10 columns]

In [11]:
dta.groupby('affair').mean()

        rate_marriage        age    ...     occupation_husb   affairs
affair                              ...
0            4.329701  28.390679    ...            3.833758  0.000000
1            3.647345  30.537019    ...            3.884559  2.187243

[2 rows x 9 columns]

In [13]:
y, X = dmatrices('affair ~ rate_marriage + age + yrs_married + children + \
                  religious + educ + C(occupation) + C(occupation_husb)',
                  dta, return_type="dataframe")

In [16]:
X = X.rename(columns = {'C(occupation)[T.2.0]':'occ_2',
                        'C(occupation)[T.3.0]':'occ_3',
                        'C(occupation)[T.4.0]':'occ_4',
                        'C(occupation)[T.5.0]':'occ_5',
                        'C(occupation)[T.6.0]':'occ_6',
                        'C(occupation_husb)[T.2.0]':'occ_husb_2',
                        'C(occupation_husb)[T.3.0]':'occ_husb_3',
                        'C(occupation_husb)[T.4.0]':'occ_husb_4',
                        'C(occupation_husb)[T.5.0]':'occ_husb_5',
                        'C(occupation_husb)[T.6.0]':'occ_husb_6'})

In [17]:
X

      Intercept  occ_2  occ_3  ...   children  religious  educ
0           1.0    1.0    0.0  ...        3.0        3.0  17.0
1           1.0    0.0    1.0  ...        3.0        1.0  14.0
2           1.0    0.0    1.0  ...        0.0        1.0  16.0
3           1.0    0.0    0.0  ...        4.0        3.0  16.0
4           1.0    0.0    1.0  ...        1.0        1.0  14.0
5           1.0    0.0    1.0  ...        0.0        2.0  14.0
6           1.0    0.0    0.0  ...        5.5        2.0  12.0
7           1.0    1.0    0.0  ...        5.5        2.0  12.0
8           1.0    0.0    1.0  ...        0.0        2.0  12.0
9           1.0    0.0    1.0  ...        0.0        1.0  16.0
10          1.0    0.0    1.0  ...        2.0        1.0  16.0
11          1.0    0.0    1.0  ...        2.0        3.0  14.0
12          1.0    1.0    0.0  ...        5.5        1.0  12.0
13          1.0    0.0    1.0  ...        0.0        2.0  14.0
14          1.0    0.0    0.0  ...        1.0        1.0  14.0
15          1.0    0.0    1.0  ...        2.0        2.0  14.0
16          1.0    0.0    1.0  ...        1.0        1.0  12.0
17          1.0    0.0    0.0  ...        5.5        4.0  14.0
18          1.0    0.0    0.0  ...        2.0        2.0  20.0
19          1.0    0.0    0.0  ...        0.0        2.0  16.0
20          1.0    0.0    1.0  ...        0.0        2.0  14.0
21          1.0    0.0    1.0  ...        5.5        2.0   9.0
22          1.0    0.0    0.0  ...        5.5        3.0  12.0
23          1.0    0.0    1.0  ...        2.0        4.0  20.0
24          1.0    0.0    0.0  ...        1.0        2.0  12.0
25          1.0    0.0    0.0  ...        0.0        3.0  16.0
26          1.0    1.0    0.0  ...        2.0        2.0  12.0
27          1.0    0.0    1.0  ...        1.0        3.0  12.0
28          1.0    0.0    0.0  ...        2.0        2.0  12.0
29          1.0    0.0    1.0  ...        1.0        1.0  14.0
...         ...    ...    ...  ...        ...        ...   ...
6336        1.0    0.0    0.0  ...        4.0        3.0  14.0
6337        1.0    0.0    0.0  ...        0.0        4.0  14.0
6338        1.0    1.0    0.0  ...        2.0        3.0  12.0
6339        1.0    0.0    0.0  ...        3.0        3.0  16.0
6340        1.0    0.0    0.0  ...        3.0        3.0  16.0
6341        1.0    0.0    0.0  ...        1.0        2.0  14.0
6342        1.0    0.0    0.0  ...        0.0        2.0  16.0
6343        1.0    0.0    1.0  ...        0.0        4.0  12.0
6344        1.0    0.0    1.0  ...        2.0        2.0  12.0
6345        1.0    0.0    1.0  ...        1.0        3.0  12.0
6346        1.0    0.0    0.0  ...        0.0        4.0  14.0
6347        1.0    0.0    1.0  ...        1.0        2.0  12.0
6348        1.0    0.0    0.0  ...        0.0        4.0  20.0
6349        1.0    0.0    0.0  ...        3.0        3.0  14.0
6350        1.0    0.0    1.0  ...        2.0        4.0  14.0
6351        1.0    0.0    1.0  ...        0.0        2.0  16.0
6352        1.0    0.0    1.0  ...        2.0        4.0  12.0
6353        1.0    0.0    1.0  ...        2.0        2.0  14.0
6354        1.0    0.0    1.0  ...        4.0        4.0  12.0
6355        1.0    0.0    1.0  ...        0.0        3.0  12.0
6356        1.0    0.0    1.0  ...        3.0        3.0  12.0
6357        1.0    0.0    0.0  ...        4.0        2.0  14.0
6358        1.0    0.0    1.0  ...        2.0        4.0  14.0
6359        1.0    0.0    0.0  ...        0.0        3.0  16.0
6360        1.0    0.0    1.0  ...        0.0        2.0  14.0
6361        1.0    0.0    0.0  ...        2.0        3.0  17.0
6362        1.0    0.0    0.0  ...        1.0        1.0  16.0
6363        1.0    0.0    1.0  ...        0.0        2.0  14.0
6364        1.0    0.0    1.0  ...        1.0        3.0  14.0
6365        1.0    1.0    0.0  ...        0.0        2.0  16.0

[6366 rows x 17 columns]

In [18]:
y = np.ravel(y)

In [19]:
regressor=LogisticRegression()
regressor.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
regressor.score(X,y)

0.7258875274897895

In [21]:
regressor.coef_

array([[ 1.48983606,  0.1880664 ,  0.49894812,  0.25066814,  0.839008  ,
         0.83390825,  0.19063622,  0.2978329 ,  0.16140914,  0.18777109,
         0.19401647, -0.70311973, -0.05841813,  0.10567669,  0.01691983,
        -0.37113512,  0.00401584]])

In [33]:
a=np.squeeze(regressor.coef_,axis=0)
a.shape

(17,)

In [30]:
X.columns.shape

(17,)

In [41]:
pd.DataFrame(list(zip(X.columns,a)))

                0         1
0       Intercept  1.489836
1           occ_2  0.188066
2           occ_3  0.498948
3           occ_4  0.250668
4           occ_5  0.839008
5           occ_6  0.833908
6      occ_husb_2  0.190636
7      occ_husb_3  0.297833
8      occ_husb_4  0.161409
9      occ_husb_5  0.187771
10     occ_husb_6  0.194016
11  rate_marriage -0.703120
12            age -0.058418
13    yrs_married  0.105677
14       children  0.016920
15      religious -0.371135
16           educ  0.004016

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [45]:
model=LogisticRegression()

In [46]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
y_pred=model.predict(X_test)

In [50]:
accuracy_score(y_test,y_pred)

0.7298429319371728

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(y_test,y_pred)

array([[1169,  134],
       [ 382,  225]], dtype=int64)